FROM nvcr.io/nvidia/pytorch:19.12-py3

#ARG HCP_CONT
#ENV HCP_CONT=$HCP_CONT

WORKDIR /root
COPY requirements_HCP.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

#COPY copy_dataset_HCP.py copy_dataset_HCP.py
COPY ./config/credentials .aws/credentials

#CMD python3 copy_dataset_HCP.py -p $HCP_CONT
