FROM nvcr.io/nvidia/pytorch:19.12-py3

WORKDIR /root
COPY ./doc_scripts/requirements_HCP.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

WORKDIR /root
COPY ./doc_scripts/copy_dataset_HCP.py copy_dataset_HCP.py
COPY ./config/credentials .aws/credentials
