FROM nvcr.io/nvidia/pytorch:19.12-py3

#WORKDIR /root
#ADD ./train/model /root/model/
#ADD model /root/

#COPY ./train/requirements.txt requirements.txt
#RUN pip install --no-cache-dir -r requirements.txt
#RUN rm requirements.txt


#RUN echo TEST:${HCP}
#ENV {}
#RUN mkdir HCP
#cp -r lol/* shara/ && cd shara
#python3 main.py --model_name "cAAE" --z_dim "128"
CMD bash
#CMD ["python3", "copy_dataset.py"]
